spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: false
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://database-cupofcoffee-user.c4a53dgythlg.ap-northeast-2.rds.amazonaws.com:3306/cupofcoffee-schema?useSSL=true&characterEncoding=UTF-8
    username: saranghein
    password: saranghein